insert into users (userid,userpw,username,mobile,useremail,userdt) values('dolphin','1234','돌고래','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('duck','1234','오리','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('swan','1234','백조','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('shark','1234','상어','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('dragon','1234','용','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('owl','1234','올빼미','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('elephant','1234','코끼리','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('camel','1234','낙타','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('giraffe','1234','기린','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('parrot','1234','앵무새','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('chameleon','1234','카멜레온','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('lion','1234','사자','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('tiger','1234','호랑이','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('sheep','1234','양','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('dog','1234','개','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('mouse','1234','생쥐','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('leopard','1234','표범','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('pigeon','1234','비둘기','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('whale','1234','고래','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('cat','1234','고양이','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('crow','1234','까마귀','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('zebra','1234','얼룩말','01012341234','email@email.com',now());
insert into users (userid,userpw,username,mobile,useremail,userdt) values('monkey','1234','원숭이','01012341234','email@email.com',now());
insert into board (userid,subject,content,date) values('monkey','나는 원숭이^_^','나는 원숭이^_^',now());
insert into board (userid,subject,content,date) values('cat','나는 고양이^_^','나는 고양이^_^',now());
insert into board (userid,subject,content,date) values('dog','나는 개^_^','나는 개^_^',now());
insert into board (userid,subject,content,date) values('crow','나는 crow^_^','나는 crow^_^',now());
insert into board (userid,subject,content,date) values('mouse','나는 mouse^_^','나는 mouse^_^',now());
insert into board (userid,subject,content,date) values('sheep','나는 sheep^_^','나는 sheep^_^',now());
insert into board (userid,subject,content,date) values('pigeon','999999999999^_^','9999999999^_^',now());
insert into board (userid,subject,content,date) values('lion','lion King^_^','lion is King^_^',now());

select * from users; 
select * from board; 